### PR TITLE
2018e update and CLDR 33.1 and fixed generics stuff for older version of delphi

### PR DESCRIPTION
**Pull request by mbtaylor1982**
1) Updated to TZDB 2018e
2) Updated to CLDR 33.1 Windows TZ alias's
3) Added SupportsGenerics IFDEF to make compatible with Delphi versions 6 -> 2007
4) Fixed a bug in the TBundledTimeZone.Destroy where FPeriods ould be freed even if it was nil. happened when the TZ passed in the constructor was invalid.

### CODE REVIEW

**Comment by pavkam** [comment]
I wouldn't bother with pre-XE Delphi-s. Actually I am curious how many people still use D6?

**Comment by pavkam** [comment]
Merged.

**Comment by pavkam** [comment]
Thanks @mbtaylor1982

**Comment by petr-nehez** [comment]
I use a lot e.g. D2010 on legacy projects :wink:

**Comment by pavkam** [comment]
@petr-nehez - noted. Thanks.

**Pull request merged**
