### PR TITLE
Replace Contnrs with Generics.Dictionary

### PR DESCRIPTION
**Pull request by ccy**

### CODE REVIEW

**Comment by pavkam** [comment]
Thanks @ccy, I'll take a look.

**Comment by mbtaylor1982** [comment]
With out doing too much work I don't think we can simply change TBucketList for TDictionary as it would prevent using the TZDB in pre-generics versions of Delphi and FPC. Maybe using a TStringList to store the year as a string and in the corresponding object property store a pointer to the list of rules for the year?

I'm not sure if this is the best approach but I reasonable sure it will be supported in both older and newer versions of Delphi and FPC and on mobile targets too.

**Comment by pavkam** [comment]
@ccy A hash-based dictionary in normal cases has better performance for more than 10 items. It is better to use a dictionary in most cases in which indexing is by non-integer key.

I chose those classes exactly because I wanted compatibility with Delphi 7 (I think!) and FPC 2.2.

Also I wanted to avoid the use of Generics in Delphi XE at all costs, due to the "**bugginess**" of the compiler.

I suggest the easiest way, in order to ensure compatibility, is to IFDEF to TDictionary for whatever is the newest version of the compiler that supports iOS/Android. everything else would use the old containers.

Alex.

**Comment by mbtaylor1982** [comment]
@pavkam looking at it maybe an $IFDEF is the best approach to maintain performance, I was looking at possibly using THashedStringList to replace TBucketList but I'm not 100% sure it was available in Delphi 7, also I fear the int -> str and str -> int conversion involved would impact performance. 

The reason I didn't initially say use an $IFDEF is it makes testing difficult as you need multiple development environments setup, I was looking for a fix using the lowest common denominator.

**Comment by pavkam** [comment]
@mbtaylor1982, yeah, that's understandable. **IFDEF**s are evil. That being said, you are correct we have to IFDEF for newest version to use _TDictionary_.

**Comment by pavkam** [comment]
I will merge this PR. I think there is no merit in keeping old versions of Delphi alive.
As long as FPC works I am OK.

**Pull request merged**
